# Here goes nothin'

version: "2"

services:

    consul1:
        image: "skunkworxs/consul:latest"
        container_name: "consul_server1"
        hostname: "consul_server1"
        ports:
          - "8400:8400"
          - "8500:8500"
          - "8600:8600"
        command: "-server -bootstrap-expect 3 -ui-dir /ui"
      consul2:
        image: "skunkworxs/consul:latest"
        container_name: "consul_server2"
        hostname: "consul_server2"
        expose:
          - "8400"
          - "8500"
          - "8600"
        command: "-server -join consul_server1"
        depends_on:
          - consul_server1
      consul3:
        image: "skunkworxs/consul:latest"
        container_name: "consul_server3"
        hostname: "consul_server3"
        expose:
          - "8400"
          - "8500"
          - "8600"
        command: "-server -join consul_server1"
        depends_on:
          - consul_server1
